=== sergiomarchio/SolvdTACourseProjects/CarFactory/src/main/resources/xsd/car_model.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:include schemaLocation="paint_color.xsd"/>
    <xsd:include schemaLocation="brand.xsd"/>

    <xsd:element name="car_model" type="CarModel"/>

    <xsd:complexType name="CarModel">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="year" type="xsd:gYear"/>
            <xsd:element name="fuel_type" type="xsd:string"/>
            <xsd:element name="unitary_price" type="xsd:double"/>
            <xsd:element name="brand" type="Brand"/>
            <xsd:element name="zip_code" type="xsd:string" minOccurs="0"/>
            <xsd:element name="paint_colors" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="paint_color" type="PaintColor" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>

        <xsd:attribute name="id" type="xsd:long" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== sergiomarchio/SolvdTACourseProjects/CarFactory/src/main/resources/xml/car_model.xml
<?xml version="1.0" encoding="UTF-8" ?>
<car_model id="404"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/car_model.xsd">
    <name>Just A Model</name>
    <type>Compact</type>
    <year>2021</year>
    <fuel_type>Electric</fuel_type>
    <unitary_price>50000</unitary_price>
    <brand id="101">
        <name>UFO</name>
    </brand>
    <paint_colors>
        <paint_color id="99">
            <name>Fuchsia</name>
        </paint_color>
        <paint_color id="55">
            <name>Lime green</name>
        </paint_color>
    </paint_colors>
</car_model>
